### ISSUE TITLE
Is Gunicorn not recommended anymore in latest Uvicorn release (>=0.30.0)?

### ISSUE THREAD

**Issue by shawn-yang-google** [Kludex/monorepo#29]
From the post https://fastapiexpert.com/blog/2024/05/28/uvicorn-0300-release/.
```
When used with Uvicorn, Gunicorn would act as a process manager and Uvicorn would act as the server handling the requests.
However, this approach is not recommended anymore.
```
The Gunicorn is not recommended anymore.

From the official doc:
```
[Built-in](https://www.uvicorn.org/deployment/#built-in)
Uvicorn includes a --workers option that allows you to run multiple worker processes.
...
[Gunicorn](https://www.uvicorn.org/deployment/#gunicorn)
...
Gunicorn is probably the simplest way to run and manage Uvicorn in a production setting. Uvicorn includes a gunicorn worker class that means you can get set up with very little configuration.
...
```
Both `Built-in` and `Gunicorn` are recommended, and `Gunicorn` sounds better (`simplest way`).

Is Build-in or Gunicorn the recommended way for process manager?
If Gunicorn is not recommended, is there any reason?

**Comment by Kludex** [comment]
I need more motivation to update the docs.

The best approach would be to deploy uvicorn with a single worker in a container.

None of the multiprocessing approaches is recommended given the complexity. If you do want/need for some reason, Uvicorn now has a process manager, giving the same functionality as gunicorn.

**Comment by Kludex** [comment]
If Google sponsors me, maybe we can bring the docs up-to-date faster. 🫣
